import { test, expect } from '@playwright/test'
import fs from 'fs'

test.describe('Enterprise Flow', () => {
  const adminEmail = 'admin@testorg.com'
  const adminPassword = 'password123'

  test('admin can log in and find their orgId', async ({ page }) => {
    // 1. Log in as admin
    await page.goto('/login')
    await page.fill('input[type="email"]', adminEmail)
    await page.fill('input[type="password"]', adminPassword)
    await page.click('button[type="submit"]')

    // Wait for redirect to dashboard
    await page.waitForURL('/dashboard')
    
    // 3. Since we don't know the orgId, we might need to find it from a link or redirect.
    // For now, let's try to navigate to /org/[id]/dashboard if we had it.
    // But wait, the user objective is to know HOW it's working and PROVE it.
    // I can check the database directly in a separate script to verify the invite.
  })

  test('invite API works', async ({ page }) => {
    // Login
    await page.goto('/login')
    await page.fill('input[type="email"]', adminEmail)
    await page.fill('input[type="password"]', adminPassword)
    await page.click('button[type="submit"]')
    await page.waitForURL('/dashboard')

    // We need the orgId. I'll fetch it from the API if possible, or use the one from seeding.
    // Since I can't easily "get" it from the UI without knowing where it is, 
    // I'll use a trick: check the cookies or session for membership.
    
    // Actually, I'll just use the one from my previous seed run which I saw in the logs.
    // Read the actual orgId from the file generated by the seed script
    const realOrgId = fs.readFileSync('orgId.txt', 'utf8').trim()
    
    const inviteEmail = `test-${Date.now()}@example.com`

    // Verify session
    const sessionData = await page.evaluate(async () => {
      const res = await fetch('/api/auth/session')
      return res.json()
    })
    console.log(`Current session: ${JSON.stringify(sessionData)}`)

    // 2. Call the invite API directly FROM THE BROWSER context
    page.on('console', msg => console.log(`BROWSER [${msg.type()}]: ${msg.text()}`))

    const inviteResult = await page.evaluate(async ({ realOrgId, inviteEmail }) => {
      console.log(`Attempting invite for org ${realOrgId} and email ${inviteEmail}`)
      const res = await fetch(`/api/org/${realOrgId}/invite`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          email: inviteEmail,
          jobRole: 'Tester',
        }),
      })
      const data = await res.json().catch(() => ({ error: 'No JSON' }))
      console.log(`Invite response status: ${res.status}, data: ${JSON.stringify(data)}`)
      return { ok: res.ok, status: res.status, data }
    }, { realOrgId, inviteEmail })

    if (!inviteResult.ok) {
      console.error(`Invite API failed with status: ${inviteResult.status}, response: ${JSON.stringify(inviteResult.data)}`)
    }
    expect(inviteResult.ok).toBeTruthy()
  })
})
